// <auto-generated />
using System;
using System.Collections.Generic;
using MUEats.Identity.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MUEats.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MUEats.Identity.Core.Domain.Role.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MUEats.Identity.Core.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmailAddress", "MUEats.Identity.Core.Domain.User.User.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email_address");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MUEats.Identity.Core.Domain.Role.Role", b =>
                {
                    b.OwnsMany("MUEats.Identity.Core.Domain.Role.ValueObjects.RoleRequirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("role_id")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.Property<string>("ValueName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("value_name");

                            b1.HasKey("role_id", "ValueName")
                                .HasName("pk_role_requirements");

                            b1.ToTable("role_requirements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("role_id")
                                .HasConstraintName("fk_role_requirements_roles_role_id");
                        });

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("MUEats.Identity.Core.Domain.User.User", b =>
                {
                    b.OwnsMany("MUEats.Identity.Core.Domain.User.ValueObjects.UserAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.HasKey("user_id", "Key")
                                .HasName("pk_user_attributes");

                            b1.ToTable("user_attributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_attributes_users_user_id");
                        });

                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
